name: Build and Deploy app to GitHub Pages
description: Build and Deploy your App to GitHub Pages
branding:
  icon: book-open
  color: yellow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install NPM packages
      run: npm install && npm update caniuse-lite browserslist

    - name: Build project
      run: npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build

#     - name: Deploy to gh-pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./build
